stages:
  - build
  - deploy

job1:
  stage: build
  script:
    - cd /home/backend/test-center
    - git pull origin test
    - mvn clean
    - mvn package
  tags:
    [test]
  only:
    [test]

job2:
  stage: deploy
  script:
    - sudo systemctl restart backend.service
  tags:
    [test]
  only:
    [test]