stages:
  - build
  - deploy

job1:
  stage: build
  script:
    - cd /home/backend/gre-center
    - git pull origin gre
    - mvn clean
    - mvn package
  tags:
    [gre]
  only:
    [gre]

job2:
  stage: deploy
  script:
    - sudo systemctl restart backend.service
  tags:
    [gre]
  only:
    [gre]