package com.ztc.testcenter.question.gre.domain;

/**
 * Created by Yubar on 2/23/2017.
 */
public enum QuestionType {
    GRE_DATA_INTERPRETATION_SET,
    GRE_DATA_INTERPRETATION_SET_SINGLE_ANSWER,
    GRE_DATA_INTERPRETATION_SET_MULTIPLE_ANSWER,
    GRE_DATA_INTERPRETATION_SET_NUMERIC,
    GRE_NUMERIC,
    GRE_NUMERIC_FRACTION,
    GRE_QUANTITATIVE_COMPARISON,
    GRE_QUANTITATIVE_SINGLE_ANSWER,
    GRE_QUANTITATIVE_MULTIPLE_ANSWER,
    GRE_READING_COMPREHENSION_SHORT,
    GRE_READING_COMPREHENSION_MEDIUM,
    GRE_READING_COMPREHENSION_LONG,
    GRE_READING_COMPREHENSION_PARAGRAPH_ARGUMENT,
    GRE_READING_COMPREHENSION_SINGLE_ANSWER,
    GRE_READING_COMPREHENSION_MULTIPLE_ANSWER,
    GRE_READING_COMPREHENSION_SELECT_IN_PASSAGE,
    GRE_SENTENCE_EQUIVALENCE,
    GRE_TEXT_COMPLETION_ONE_BLANK,
    GRE_TEXT_COMPLETION_TWO_BLANK,
    GRE_TEXT_COMPLETION_THREE_BLANK,
    GRE_WRITING_ISSUE,
    GRE_WRITING_ARGUMENT;
}
