package com.ztc.testcenter.domain.question;

/**
 * Created by Yubar on 2/23/2017.
 */
public enum QuestionType {
    GRE_DATA_INTERPRETATION_SET,
    GRE_DATA_INTERPRETATION_SET_SINGLE_ANSWER,
    GRE_DATA_INTERPRETATION_SET_MULTIPLE_ANSWER,
    GRE_DATA_INTERPRETATION_SET_NUMERIC,
    GRE_NUMERIC,
    GRE_QUANTITATIVE_COMPARISON,
    GRE_QUANTITATIVE_SINGLE_ANSWER,
    GRE_QUANTITATIVE_MULTIPLE_ANSWER,
    GRE_READING_COMPREHENSION,
    GRE_READING_COMPREHENSION_SINGLE_ANSWER,
    GRE_READING_COMPREHENSION_MULTIPLE_ANSWER,
    GRE_READING_COMPREHENSION_SELECT_IN_PASSAGE,
    GRE_SENTENCE_EQUIVALENCE,
    GRE_TEXT_COMPLETION,
    GRE_WRITING
}
